const STORAGE_KEY='ksrct_certificate_portal_v1';
const users={
 student:{email:'prasanna@gmail.com',password:'student123',name:'Prasanna M',role:'Student',dept:'III Year - EEE',reg:'22EE123'},
 hod:{email:'hod@ksrct.ac.in',password:'hod123',name:'Dr. EEE HOD',role:'HOD / Verifier',dept:'Electrical and Electronics Engineering',reg:'HOD-EEE'}
};
const seed=[
 {id:'CERT-1001',title:'NPTEL – Internet of Things',category:'NPTEL',date:'2026-07-20',status:'Approved',owner:'Prasanna M',ownerReg:'22EE123',fileName:'nptel-iot.pdf',fileData:null,description:'NPTEL certificate for Internet of Things.'},
 {id:'CERT-1002',title:'Summer Internship – SCG Ex d Tech',category:'Internship',date:'2026-07-18',status:'Pending',owner:'Prasanna M',ownerReg:'22EE123',fileName:'internship-certificate.jpg',fileData:'assets/ksrct-campus.jpg',description:'Summer internship completion certificate.'},
 {id:'CERT-1003',title:'Workshop on PLC & SCADA',category:'Workshop',date:'2026-07-15',status:'Approved',owner:'Prasanna M',ownerReg:'22EE123',fileName:'plc-workshop.pdf',fileData:null,description:'Workshop participation certificate.'},
 {id:'CERT-1004',title:'AICTE IDE Bootcamp',category:'Hackathon',date:'2026-07-10',status:'Rejected',owner:'Prasanna M',ownerReg:'22EE123',fileName:'aicte-bootcamp.pdf',fileData:null,description:'AICTE IDE Bootcamp participation certificate.'},
 {id:'CERT-1005',title:'NSS Participation',category:'NSS',date:'2026-07-05',status:'Approved',owner:'Prasanna M',ownerReg:'22EE123',fileName:'nss.pdf',fileData:null,description:'NSS participation certificate.'}
];
const state={user:null,page:'dashboard',certificates:loadCerts(),search:'',category:'All',status:'All'};
function loadCerts(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(x)?x:seed}catch{return seed}}
function saveCerts(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.certificates))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg,type='success'){const root=document.getElementById('toastRoot');const el=document.createElement('div');el.className='toast '+type;el.textContent=msg;root.appendChild(el);setTimeout(()=>el.remove(),3200)}
function fmtDate(d){return new Date(d+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function initials(name){return name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function statusClass(s){return s.toLowerCase()}
function getMine(){return state.certificates.filter(c=>c.ownerReg===state.user.reg)}
function stats(list){return {total:list.length,approved:list.filter(c=>c.status==='Approved').length,pending:list.filter(c=>c.status==='Pending').length,rejected:list.filter(c=>c.status==='Rejected').length}}
function filtered(list){return list.filter(c=>{const q=state.search.toLowerCase();return (!q||[c.title,c.category,c.owner,c.ownerReg,c.id].some(v=>String(v).toLowerCase().includes(q)))&&(state.category==='All'||c.category===state.category)&&(state.status==='All'||c.status===state.status)})}
function statCards(s){return `<div class="stats-grid"><div class="stat-card"><div><strong>${s.total}</strong><span>Total Certificates</span></div><div class="icon">▣</div></div><div class="stat-card"><div><strong>${s.approved}</strong><span>Approved</span></div><div class="icon">✓</div></div><div class="stat-card"><div><strong>${s.pending}</strong><span>Pending</span></div><div class="icon">◷</div></div><div class="stat-card"><div><strong>${s.rejected}</strong><span>Rejected</span></div><div class="icon">×</div></div></div>`}
function certTable(list,showOwner=false){if(!list.length)return `<div class="empty"><strong>No certificates found</strong>Try changing your filters or upload a new certificate.</div>`;return `<div class="table-wrap"><table class="table"><thead><tr><th>Title</th><th>Category</th>${showOwner?'<th>Student</th>':''}<th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>${list.map(c=>`<tr><td><div class="certificate-row-title">${esc(c.title)}</div><div class="muted">${esc(c.id)} · ${esc(c.fileName||'file')}</div></td><td>${esc(c.category)}</td>${showOwner?`<td>${esc(c.owner)}<div class="muted">${esc(c.ownerReg)}</div></td>`:''}<td>${fmtDate(c.date)}</td><td><span class="status ${statusClass(c.status)}">${c.status}</span></td><td><button class="link-btn" onclick="viewCert('${c.id}')">View</button> ${state.user.role!=='Student'&&c.status==='Pending'?`<button class="link-btn" onclick="verifyCert('${c.id}')">Verify</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
function renderNav(){const student=state.user.role==='Student';const items=student?[['dashboard','▦','Dashboard'],['certificates','▤','My Certificates'],['upload','＋','Upload Certificate'],['profile','♙','My Profile'],['notifications','♧','Notifications']]:[['dashboard','▦','Dashboard'],['certificates','▤','All Certificates'],['verification','✓','Verification Queue'],['students','♙','Students'],['reports','▤','Reports'],['profile','⚙','Profile']];document.getElementById('sidebarNav').innerHTML=items.map(([p,i,t])=>`<button class="nav-item ${state.page===p?'active':''}" data-page="${p}"><span>${i}</span>${t}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page))}
function render(){if(!state.user)return;document.getElementById('headerName').textContent=state.user.name;document.getElementById('headerRole').textContent=state.user.role;document.getElementById('headerAvatar').textContent=initials(state.user.name);document.getElementById('pageCrumb').textContent=titleFor(state.page);renderNav();const pc=document.getElementById('pageContent');pc.innerHTML=pages[state.page]?pages[state.page]():pages.dashboard();bindPage();}
function titleFor(p){return ({dashboard:'Dashboard',certificates:state.user.role==='Student'?'My Certificates':'Certificate Management',upload:'Upload Certificate',profile:'My Profile',notifications:'Notifications',verification:'Verification Queue',students:'Students',reports:'Reports',support:'Help & Support'})[p]||'Dashboard'}
function navigate(p){state.page=p;state.search='';state.category='All';state.status='All';render();document.querySelector('.sidebar')?.classList.remove('open')}
function pageHead(title,sub,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`}
const pages={
 dashboard(){const mine=getMine(), s=stats(mine);if(state.user.role==='Student')return `${pageHead('Welcome Back, '+esc(state.user.name)+'! 👋','Here is the latest status of your certificates.',`<button class="primary-btn" onclick="navigate('upload')">+ Upload Certificate</button>`)}${statCards(s)}<div class="grid-2"><div class="card"><div class="card-head"><h3>Recent Uploads</h3><button onclick="navigate('certificates')">View All →</button></div>${certTable(mine.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5))}</div><div class="card"><div class="card-head"><h3>Upload Certificate</h3></div><div class="card-body"><div class="upload-box"><div class="cloud">☁</div><h3>Upload your certificates</h3><p>PDF, JPG, PNG (Max. 10MB)</p><button class="primary-btn" onclick="navigate('upload')">+ Upload Now</button></div></div></div></div>`;
 const all=state.certificates,adminS=stats(all);return `${pageHead('HOD Dashboard','Department of Electrical and Electronics Engineering',`<button class="secondary-btn" onclick="exportCSV()">Export to CSV</button><button class="primary-btn" onclick="navigate('verification')">Review Pending</button>`)}${statCards(adminS)}<div class="grid-2"><div class="card"><div class="card-head"><h3>Certificate Status Overview</h3><button onclick="navigate('certificates')">View All →</button></div><div class="card-body"><div class="chart-row"><div class="chart-item"><span>Approved</span><div class="progress"><div style="width:${adminS.total?Math.round(adminS.approved/adminS.total*100):0}%"></div></div><strong>${adminS.approved}</strong></div><div class="chart-item"><span>Pending</span><div class="progress"><div style="width:${adminS.total?Math.round(adminS.pending/adminS.total*100):0}%"></div></div><strong>${adminS.pending}</strong></div><div class="chart-item"><span>Rejected</span><div class="progress"><div style="width:${adminS.total?Math.round(adminS.rejected/adminS.total*100):0}%"></div></div><strong>${adminS.rejected}</strong></div></div></div></div><div class="card"><div class="card-head"><h3>Recent Activities</h3></div><div class="card-body activity-list">${all.slice(-5).reverse().map(c=>`<div class="activity"><div class="activity-dot"></div><div><strong>${esc(c.owner)} — ${esc(c.title)}</strong><span>${c.status} · ${fmtDate(c.date)}</span></div></div>`).join('')}</div></div></div>`},
 certificates(){const list=state.user.role==='Student'?getMine():state.certificates;const f=filtered(list);return `${pageHead(state.user.role==='Student'?'My Certificates':'Certificate Management',state.user.role==='Student'?'View and track all certificates submitted by you.':'Search, filter and manage certificates from students.',state.user.role==='Student'?`<button class="primary-btn" onclick="navigate('upload')">+ Upload Certificate</button>`:`<button class="secondary-btn" onclick="exportCSV()">Export to CSV</button>`)}<div class="toolbar"><div class="search-row"><input id="searchInput" value="${esc(state.search)}" placeholder="Search by title, category, student or ID..." /><select id="categoryFilter" class="filter-select"><option>All</option>${[...new Set(state.certificates.map(c=>c.category))].map(x=>`<option ${state.category===x?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="statusFilter" class="filter-select"><option>All</option><option ${state.status==='Approved'?'selected':''}>Approved</option><option ${state.status==='Pending'?'selected':''}>Pending</option><option ${state.status==='Rejected'?'selected':''}>Rejected</option></select><span class="muted" style="margin-left:auto;font-size:11px">${f.length} result(s)</span></div></div><div class="card">${certTable(f,state.user.role!=='Student')}</div>`},
 upload(){return `${pageHead('Upload Certificate','Submit a new certificate for verification.') }<div class="card"><div class="card-body"><form id="uploadForm"><div class="form-grid"><div><label>Certificate Title *</label><input id="certTitle" required placeholder="e.g. NPTEL – Internet of Things" /></div><div><label>Category *</label><select id="certCategory" required><option value="">Select Category</option><option>NPTEL</option><option>Internship</option><option>Workshop</option><option>Hackathon</option><option>NSS</option><option>Sports</option><option>Academic</option><option>Other</option></select></div><div><label>Date of Issue *</label><input id="certDate" type="date" required value="2026-08-17" /></div><div><label>Description</label><input id="certDescription" placeholder="Optional description" /></div><div class="field-full"><label>Certificate File *</label><div id="dropzone" class="dropzone"><div style="font-size:32px">☁</div><strong>Drag & Drop your certificate here</strong><div class="muted" style="font-size:11px;margin-top:5px">or click to choose a PDF, JPG or PNG (max 10MB)</div><div id="fileName" class="file-name"></div></div><input id="uploadFile" type="file" accept=".pdf,.jpg,.jpeg,.png" hidden required /></div></div><div class="actions" style="justify-content:flex-end;margin-top:18px"><button type="reset" class="secondary-btn">Reset</button><button type="submit" class="primary-btn">Upload Certificate</button></div></form></div></div>`},
 verification(){const pending=filtered(state.certificates.filter(c=>c.status==='Pending'));return `${pageHead('Verification Queue','Review pending student certificates and take action.',`<span class="status pending">${pending.length} Pending</span>`)}<div class="card">${certTable(pending,true)}</div>`},
 students(){const groups={};state.certificates.forEach(c=>{groups[c.ownerReg]??={name:c.owner,reg:c.ownerReg,total:0,approved:0,pending:0,rejected:0};groups[c.ownerReg].total++;groups[c.ownerReg][c.status.toLowerCase()]++});const rows=Object.values(groups);return `${pageHead('Students','Certificate activity by student.')}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>Register No.</th><th>Total</th><th>Approved</th><th>Pending</th><th>Rejected</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.name)}</strong></td><td>${esc(r.reg)}</td><td>${r.total}</td><td>${r.approved}</td><td>${r.pending}</td><td>${r.rejected}</td><td><button class="link-btn" onclick="showStudent('${esc(r.reg)}')">View</button></td></tr>`).join('')}</tbody></table></div></div>`},
 reports(){const s=stats(state.certificates);return `${pageHead('Reports','Generate and export certificate management reports.',`<button class="primary-btn" onclick="printReport()">Print Report</button><button class="secondary-btn" onclick="exportCSV()">Export CSV</button>`)}${statCards(s)}<div class="card"><div class="card-head"><h3>Category Breakdown</h3></div><div class="card-body">${[...new Set(state.certificates.map(c=>c.category))].map(cat=>{const n=state.certificates.filter(c=>c.category===cat).length;return `<div class="chart-item" style="margin-bottom:12px"><span>${esc(cat)}</span><div class="progress"><div style="width:${Math.round(n/state.certificates.length*100)}%"></div></div><strong>${n}</strong></div>`}).join('')}</div></div>`},
 profile(){const u=state.user;return `${pageHead('My Profile','Your portal account and academic details.')}<div class="card"><div class="card-body"><div class="profile-card"><div class="profile-avatar">${initials(u.name)}</div><div><h2 style="margin:0 0 4px">${esc(u.name)}</h2><div class="muted">${esc(u.role)}</div></div></div><div class="detail-grid"><div class="detail"><span>Email</span><strong>${esc(u.email)}</strong></div><div class="detail"><span>Register No.</span><strong>${esc(u.reg)}</strong></div><div class="detail"><span>Department</span><strong>${esc(u.dept)}</strong></div></div></div></div>`},
 notifications(){return `${pageHead('Notifications','Important updates from the certificate portal.')}<div class="card"><div class="card-body activity-list"><div class="activity"><div class="activity-dot"></div><div><strong>Certificate verification update</strong><span>Your Summer Internship certificate is pending review.</span></div></div><div class="activity"><div class="activity-dot"></div><div><strong>NPTEL certificate approved</strong><span>Your certificate was approved by the department.</span></div></div><div class="activity"><div class="activity-dot"></div><div><strong>Certificate rejected</strong><span>AICTE IDE Bootcamp certificate needs correction or resubmission.</span></div></div></div></div>`},
 support(){return `${pageHead('Help & Support','Get help with uploading and certificate verification.')}<div class="grid-2"><div class="card"><div class="card-body"><h3>How it works</h3><ol style="line-height:2;font-size:12px;color:#53627a"><li>Upload a clear PDF, JPG or PNG.</li><li>Enter the correct title, category and issue date.</li><li>Submit the certificate.</li><li>HOD verifies it and marks Approved or Rejected.</li></ol></div></div><div class="card"><div class="card-body"><h3>Need help?</h3><p class="muted" style="font-size:12px">Contact the college administration or your department office for account and certificate issues.</p><button class="primary-btn" onclick="contactAdmin()">Contact Admin</button></div></div></div>`}
};
function bindPage(){const s=document.getElementById('searchInput');if(s)s.oninput=e=>{state.search=e.target.value;render()};const cf=document.getElementById('categoryFilter');if(cf)cf.onchange=e=>{state.category=e.target.value;render()};const sf=document.getElementById('statusFilter');if(sf)sf.onchange=e=>{state.status=e.target.value;render()};const form=document.getElementById('uploadForm');if(form)setupUpload(form)}
function setupUpload(form){const dz=document.getElementById('dropzone'),fi=document.getElementById('uploadFile'),fn=document.getElementById('fileName');dz.onclick=()=>fi.click();['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{if(e.dataTransfer.files[0]){fi.files=e.dataTransfer.files;fn.textContent=e.dataTransfer.files[0].name}});fi.onchange=()=>{fn.textContent=fi.files[0]?.name||''};form.onsubmit=async e=>{e.preventDefault();const file=fi.files[0];if(!file)return toast('Please choose a certificate file.','error');if(file.size>10*1024*1024)return toast('File exceeds the 10MB limit.','error');let data=null;if(file.type.startsWith('image/'))data=await fileToDataURL(file);const cert={id:'CERT-'+Math.floor(1000+Math.random()*9000),title:document.getElementById('certTitle').value.trim(),category:document.getElementById('certCategory').value,date:document.getElementById('certDate').value,status:'Pending',owner:state.user.name,ownerReg:state.user.reg,fileName:file.name,fileData:data,description:document.getElementById('certDescription').value.trim()};state.certificates.unshift(cert);saveCerts();toast('Certificate uploaded successfully.');navigate('certificates')}}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function viewCert(id){const c=state.certificates.find(x=>x.id===id);if(!c)return;const preview=c.fileData?`<img src="${c.fileData}" alt="Certificate preview" />`:`<div style="background:white;border:1px solid #ddd;padding:35px;text-align:center;max-width:360px"><img src="assets/ksrct-logo.png" style="width:70px"><h3>${esc(c.title)}</h3><p style="color:#65748c;font-size:12px">Certificate preview unavailable for this demo file. The uploaded filename is <b>${esc(c.fileName)}</b>.</p></div>`;modal(`<div class="verify-layout"><div class="certificate-preview">${preview}</div><div class="review-box"><div class="notice"><strong>${c.status}</strong><br>Certificate ID: ${esc(c.id)}</div><h2 style="margin:0 0 5px">${esc(c.title)}</h2><p class="muted" style="font-size:12px">${esc(c.description||'No description provided.')}</p><div class="detail-grid"><div class="detail"><span>Category</span><strong>${esc(c.category)}</strong></div><div class="detail"><span>Issue Date</span><strong>${fmtDate(c.date)}</strong></div><div class="detail"><span>Student</span><strong>${esc(c.owner)}</strong></div></div>${state.user.role!=='Student'&&c.status==='Pending'?`<div class="review-actions"><button class="primary-btn green" onclick="setStatus('${c.id}','Approved')">Approve</button><button class="danger-btn" onclick="setStatus('${c.id}','Rejected')">Reject</button></div>`:''}</div></div>`,'Certificate Details')}
function verifyCert(id){viewCert(id)}
function setStatus(id,status){const c=state.certificates.find(x=>x.id===id);if(!c)return;c.status=status;saveCerts();closeModal();toast(`Certificate ${status.toLowerCase()}.`);render()}
function showStudent(reg){const list=state.certificates.filter(c=>c.ownerReg===reg);const name=list[0]?.owner||reg;modal(`<div><h3 style="margin-top:0">${esc(name)}</h3><p class="muted">Register No: ${esc(reg)}</p>${certTable(list,false)}</div>`,'Student Certificates')}
function modal(body,title){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div></div></div>`}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function contactAdmin(){modal(`<p style="font-size:13px">For account or certificate issues, contact the department administration.</p><div class="detail-grid"><div class="detail"><span>Institution</span><strong>K.S.Rangasamy College of Technology</strong></div><div class="detail"><span>Location</span><strong>Tiruchengode, Tamil Nadu</strong></div><div class="detail"><span>Portal</span><strong>Certificate Management</strong></div></div>`,'Contact Admin')}
function exportCSV(){const rows=[['Certificate ID','Title','Category','Student','Register No','Date','Status','File'],...state.certificates.map(c=>[c.id,c.title,c.category,c.owner,c.ownerReg,c.date,c.status,c.fileName||''])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ksrct-certificates.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV report exported.')}
function printReport(){const s=stats(state.certificates);const w=window.open('','_blank');w.document.write(`<html><head><title>KSRCT Certificate Report</title><style>body{font-family:Arial;padding:35px;color:#17233b}h1{color:#082a59}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{border:1px solid #ddd;padding:8px;font-size:12px;text-align:left}</style></head><body><h1>KSRCT Certificate Management Report</h1><p>Generated: ${new Date().toLocaleString('en-IN')}</p><p>Total: ${s.total} | Approved: ${s.approved} | Pending: ${s.pending} | Rejected: ${s.rejected}</p>${certTable(state.certificates,true)}</body></html>`);w.document.close();w.print()}
function login(role,email,password){const u=users[role];if(u.email===email&&u.password===password){state.user=u;document.getElementById('loginView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden');state.page='dashboard';render();toast('Login successful.');}else toast('Invalid credentials. Use the demo credentials shown below.','error')}
document.getElementById('loginForm').onsubmit=e=>{e.preventDefault();login(document.getElementById('loginRole').value,document.getElementById('loginEmail').value.trim(),document.getElementById('loginPassword').value)};
document.getElementById('togglePassword').onclick=()=>{const p=document.getElementById('loginPassword');p.type=p.type==='password'?'text':'password'};
document.getElementById('contactAdminBtn').onclick=contactAdmin;
document.getElementById('logoutBtn').onclick=()=>{state.user=null;document.getElementById('appView').classList.add('hidden');document.getElementById('loginView').classList.remove('hidden');document.getElementById('loginPassword').value=''};
document.getElementById('mobileMenuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.getElementById('notificationBtn').onclick=()=>navigate('notifications');
document.getElementById('userMenuBtn').onclick=()=>navigate('profile');
window.navigate=navigate;window.viewCert=viewCert;window.verifyCert=verifyCert;window.setStatus=setStatus;window.showStudent=showStudent;window.closeModal=closeModal;window.exportCSV=exportCSV;window.printReport=printReport;window.contactAdmin=contactAdmin;
