export type Role = 'STUDENT' | 'STAFF' | 'CREATOR';

export const PERMISSIONS = {
  CERTIFICATE_VIEW_OWN: 'CERTIFICATE_VIEW_OWN',
  CERTIFICATE_REQUEST: 'CERTIFICATE_REQUEST',
  CERTIFICATE_UPLOAD: 'CERTIFICATE_UPLOAD',
  CERTIFICATE_DOWNLOAD: 'CERTIFICATE_DOWNLOAD',
  CERTIFICATE_VERIFY: 'CERTIFICATE_VERIFY',
  CERTIFICATE_APPROVE: 'CERTIFICATE_APPROVE',
  CERTIFICATE_REJECT: 'CERTIFICATE_REJECT',
  CERTIFICATE_ISSUE: 'CERTIFICATE_ISSUE',
  CERTIFICATE_MANAGE: 'CERTIFICATE_MANAGE',
  CERTIFICATE_TEMPLATE_CREATE: 'CERTIFICATE_TEMPLATE_CREATE',
  CERTIFICATE_TEMPLATE_EDIT: 'CERTIFICATE_TEMPLATE_EDIT',
  CERTIFICATE_TEMPLATE_DELETE: 'CERTIFICATE_TEMPLATE_DELETE',
  USER_CREATE: 'USER_CREATE',
  USER_MANAGE: 'USER_MANAGE',
  USER_DELETE: 'USER_DELETE',
  ROLE_ASSIGN: 'ROLE_ASSIGN',
  SYSTEM_SETTINGS: 'SYSTEM_SETTINGS',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
} as const;

export type Permission = keyof typeof PERMISSIONS;

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  STUDENT: [
    PERMISSIONS.CERTIFICATE_VIEW_OWN,
    PERMISSIONS.CERTIFICATE_REQUEST,
    PERMISSIONS.CERTIFICATE_UPLOAD,
    PERMISSIONS.CERTIFICATE_DOWNLOAD,
  ],
  STAFF: [
    PERMISSIONS.CERTIFICATE_VIEW_OWN,
    PERMISSIONS.CERTIFICATE_UPLOAD,
    PERMISSIONS.CERTIFICATE_DOWNLOAD,
    PERMISSIONS.CERTIFICATE_VERIFY,
    PERMISSIONS.CERTIFICATE_APPROVE,
    PERMISSIONS.CERTIFICATE_REJECT,
    PERMISSIONS.CERTIFICATE_ISSUE,
    PERMISSIONS.CERTIFICATE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  CREATOR: Object.values(PERMISSIONS) as Permission[],
};

export const hasPermission = (role: string, permission: Permission): boolean => {
  if (role === 'CREATOR' || role === 'STAFF') return true;
  const perms = ROLE_PERMISSIONS[role as Role];
  return perms ? perms.includes(permission) : false;
};
