import { Role } from '../types';

export const PERMISSIONS = {
  CERTIFICATE_VIEW_OWN: 'CERTIFICATE_VIEW_OWN',
  CERTIFICATE_REQUEST: 'CERTIFICATE_REQUEST',
  CERTIFICATE_UPLOAD: 'CERTIFICATE_UPLOAD',
  CERTIFICATE_DOWNLOAD: 'CERTIFICATE_DOWNLOAD',
  CERTIFICATE_VERIFY: 'CERTIFICATE_VERIFY',
  CERTIFICATE_APPROVE: 'CERTIFICATE_APPROVE',
  CERTIFICATE_REJECT: 'CERTIFICATE_REJECT',
  CERTIFICATE_ISSUE: 'CERTIFICATE_ISSUE',
  CERTIFICATE_MANAGE: 'CERTIFICATE_MANAGE',
  CERTIFICATE_TEMPLATE_CREATE: 'CERTIFICATE_TEMPLATE_CREATE',
  CERTIFICATE_TEMPLATE_EDIT: 'CERTIFICATE_TEMPLATE_EDIT',
  CERTIFICATE_TEMPLATE_DELETE: 'CERTIFICATE_TEMPLATE_DELETE',
  USER_CREATE: 'USER_CREATE',
  USER_MANAGE: 'USER_MANAGE',
  USER_DELETE: 'USER_DELETE',
  ROLE_ASSIGN: 'ROLE_ASSIGN',
  SYSTEM_SETTINGS: 'SYSTEM_SETTINGS',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
} as const;

export type Permission = keyof typeof PERMISSIONS;

const ALL_PERMISSIONS = Object.values(PERMISSIONS) as Permission[];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  STUDENT: [
    PERMISSIONS.CERTIFICATE_VIEW_OWN,
    PERMISSIONS.CERTIFICATE_REQUEST,
    PERMISSIONS.CERTIFICATE_UPLOAD,
    PERMISSIONS.CERTIFICATE_DOWNLOAD,
  ],
  MENTOR: [
    PERMISSIONS.CERTIFICATE_VIEW_OWN,
    PERMISSIONS.CERTIFICATE_VERIFY,
    PERMISSIONS.CERTIFICATE_APPROVE,
    PERMISSIONS.CERTIFICATE_REJECT,
    PERMISSIONS.REPORT_VIEW,
  ],
  ADVISOR: [
    PERMISSIONS.CERTIFICATE_VIEW_OWN,
    PERMISSIONS.CERTIFICATE_VERIFY,
    PERMISSIONS.CERTIFICATE_APPROVE,
    PERMISSIONS.CERTIFICATE_REJECT,
    PERMISSIONS.REPORT_VIEW,
  ],
  HOD: [
    PERMISSIONS.CERTIFICATE_VIEW_OWN,
    PERMISSIONS.CERTIFICATE_VERIFY,
    PERMISSIONS.CERTIFICATE_APPROVE,
    PERMISSIONS.CERTIFICATE_REJECT,
    PERMISSIONS.CERTIFICATE_ISSUE,
    PERMISSIONS.CERTIFICATE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  STAFF: [
    PERMISSIONS.CERTIFICATE_VIEW_OWN,
    PERMISSIONS.CERTIFICATE_VERIFY,
    PERMISSIONS.CERTIFICATE_APPROVE,
    PERMISSIONS.CERTIFICATE_REJECT,
    PERMISSIONS.REPORT_VIEW,
  ],
  ADMIN: ALL_PERMISSIONS,
  CREATOR: ALL_PERMISSIONS,
};

export const hasPermission = (role?: Role | null, permission?: Permission): boolean => {
  if (!role || !permission) return false;
  if (role === 'CREATOR' || role === 'ADMIN' || role === 'HOD') return true;
  const perms = ROLE_PERMISSIONS[role];
  return perms ? perms.includes(permission) : false;
};

export const getRoleDisplayName = (role?: Role | string | null): string => {
  switch (role) {
    case 'STUDENT':
      return 'Student';
    case 'MENTOR':
      return 'Faculty Mentor';
    case 'ADVISOR':
      return 'Class Advisor';
    case 'HOD':
      return 'Head of Department (HOD)';
    case 'STAFF':
      return 'Faculty Staff';
    case 'ADMIN':
      return 'Department Admin';
    case 'CREATOR':
      return 'Master Creator';
    default:
      return role || 'User';
  }
};
